### PR TITLE
Adjust how 14-18 forecast tables are scraped

### PR DESCRIPTION
**Pull request by angusmoore**
Internally cached  is missing some series because the way the tables are scraped was missing some rows.

Code in `internal_data` was getting the wrong `year-average` row - previous iteration was not extracting the _list_ of rows for `grepl`. Specifically was previously incorrectly grabbing the index as:
```
> grepl("Year-average", forecast[, 2])
[1] FALSE
```
Change to:
```
> grepl("Year-average", forecast[, 2][[1]])
 [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[22] FALSE FALSE FALSE
```

Also add a test to make sure the internal data has GDP, underlying and headline for 2016 SMP (which has the in the [table](https://www.rba.gov.au/publications/smp/2016/nov/)). Previous version of internal data was missing underlying, so this test would fail previously.

### CODE REVIEW

**Comment by MattCowgill** [comment]
Ah you legend @angusmoore, this rules, thanks. I'll have a proper look later today, but looks great. Thanks for picking up on these issues.

**Review by MattCowgill — APPROVED** [review]
Thanks again @angusmoore, this is great (and somewhat embarassing)

**Comment by MattCowgill** [comment]
@angusmoore I've added you as a contributor in the package `DESCRIPTION`. If you'd prefer not to be added - or you'd like to add extra info such as your email address, ORCID ID, etc. - please let me know (or just do another commit).

**Comment by angusmoore** [comment]
Not at all, glad I could help out -- it's a great package! Happy to be included in contributors, that's very kind and definitely not necessary, this is a very small change.

**Pull request merged**
